// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.dto.model.bus;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.starterkit.springboot.brs.dto.model.user.UserDto;
import java.util.Set;

/**
 * Created by Arpit Khandelwal.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class AgencyDto {
    private String code;
    private UserDto owner;
    private Set<BusDto> buses;
    private String name;
    private String details;

    @java.lang.SuppressWarnings("all")
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    public UserDto getOwner() {
        return this.owner;
    }

    @java.lang.SuppressWarnings("all")
    public Set<BusDto> getBuses() {
        return this.buses;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDetails() {
        return this.details;
    }

    @java.lang.SuppressWarnings("all")
    public AgencyDto setCode(final String code) {
        this.code = code;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AgencyDto setOwner(final UserDto owner) {
        this.owner = owner;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AgencyDto setBuses(final Set<BusDto> buses) {
        this.buses = buses;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AgencyDto setName(final String name) {
        this.name = name;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AgencyDto setDetails(final String details) {
        this.details = details;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AgencyDto() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AgencyDto(code=" + this.getCode() + ", owner=" + this.getOwner() + ", buses=" + this.getBuses() + ", name=" + this.getName() + ", details=" + this.getDetails() + ")";
    }
}
