// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.dto.model.bus;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Created by Arpit Khandelwal.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class BusDto {
    private String code;
    private int capacity;
    private String make;

    @java.lang.SuppressWarnings("all")
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    public int getCapacity() {
        return this.capacity;
    }

    @java.lang.SuppressWarnings("all")
    public String getMake() {
        return this.make;
    }

    @java.lang.SuppressWarnings("all")
    public BusDto setCode(final String code) {
        this.code = code;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BusDto setCapacity(final int capacity) {
        this.capacity = capacity;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BusDto setMake(final String make) {
        this.make = make;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BusDto() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BusDto(code=" + this.getCode() + ", capacity=" + this.getCapacity() + ", make=" + this.getMake() + ")";
    }
}
