// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.dto.model.bus;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Created by Arpit Khandelwal.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class StopDto implements Comparable {
    private String code;
    private String name;
    private String detail;

    @Override
    public int compareTo(Object o) {
        return this.getName().compareTo(((StopDto) o).getName());
    }

    @java.lang.SuppressWarnings("all")
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDetail() {
        return this.detail;
    }

    @java.lang.SuppressWarnings("all")
    public StopDto setCode(final String code) {
        this.code = code;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public StopDto setName(final String name) {
        this.name = name;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public StopDto setDetail(final String detail) {
        this.detail = detail;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public StopDto() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "StopDto(code=" + this.getCode() + ", name=" + this.getName() + ", detail=" + this.getDetail() + ")";
    }
}
