// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.dto.model.bus;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Created by Arpit Khandelwal.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class TicketDto {
    private String id;
    private String busCode;
    private int seatNumber;
    private boolean cancellable;
    private String journeyDate;
    private String sourceStop;
    private String destinationStop;
    private String passengerName;
    private String passengerMobileNumber;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getBusCode() {
        return this.busCode;
    }

    @java.lang.SuppressWarnings("all")
    public int getSeatNumber() {
        return this.seatNumber;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isCancellable() {
        return this.cancellable;
    }

    @java.lang.SuppressWarnings("all")
    public String getJourneyDate() {
        return this.journeyDate;
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceStop() {
        return this.sourceStop;
    }

    @java.lang.SuppressWarnings("all")
    public String getDestinationStop() {
        return this.destinationStop;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassengerName() {
        return this.passengerName;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassengerMobileNumber() {
        return this.passengerMobileNumber;
    }

    @java.lang.SuppressWarnings("all")
    public TicketDto setId(final String id) {
        this.id = id;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TicketDto setBusCode(final String busCode) {
        this.busCode = busCode;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TicketDto setSeatNumber(final int seatNumber) {
        this.seatNumber = seatNumber;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TicketDto setCancellable(final boolean cancellable) {
        this.cancellable = cancellable;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TicketDto setJourneyDate(final String journeyDate) {
        this.journeyDate = journeyDate;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TicketDto setSourceStop(final String sourceStop) {
        this.sourceStop = sourceStop;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TicketDto setDestinationStop(final String destinationStop) {
        this.destinationStop = destinationStop;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TicketDto setPassengerName(final String passengerName) {
        this.passengerName = passengerName;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TicketDto setPassengerMobileNumber(final String passengerMobileNumber) {
        this.passengerMobileNumber = passengerMobileNumber;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TicketDto() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "TicketDto(id=" + this.getId() + ", busCode=" + this.getBusCode() + ", seatNumber=" + this.getSeatNumber() + ", cancellable=" + this.isCancellable() + ", journeyDate=" + this.getJourneyDate() + ", sourceStop=" + this.getSourceStop() + ", destinationStop=" + this.getDestinationStop() + ", passengerName=" + this.getPassengerName() + ", passengerMobileNumber=" + this.getPassengerMobileNumber() + ")";
    }
}
