// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.dto.model.bus;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Created by Arpit Khandelwal.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class TripDto {
    private String id;
    private int fare;
    private int journeyTime;
    private String sourceStopCode;
    private String sourceStopName;
    private String destinationStopCode;
    private String destinationStopName;
    private String busCode;
    private String agencyCode;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public int getFare() {
        return this.fare;
    }

    @java.lang.SuppressWarnings("all")
    public int getJourneyTime() {
        return this.journeyTime;
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceStopCode() {
        return this.sourceStopCode;
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceStopName() {
        return this.sourceStopName;
    }

    @java.lang.SuppressWarnings("all")
    public String getDestinationStopCode() {
        return this.destinationStopCode;
    }

    @java.lang.SuppressWarnings("all")
    public String getDestinationStopName() {
        return this.destinationStopName;
    }

    @java.lang.SuppressWarnings("all")
    public String getBusCode() {
        return this.busCode;
    }

    @java.lang.SuppressWarnings("all")
    public String getAgencyCode() {
        return this.agencyCode;
    }

    @java.lang.SuppressWarnings("all")
    public TripDto setId(final String id) {
        this.id = id;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripDto setFare(final int fare) {
        this.fare = fare;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripDto setJourneyTime(final int journeyTime) {
        this.journeyTime = journeyTime;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripDto setSourceStopCode(final String sourceStopCode) {
        this.sourceStopCode = sourceStopCode;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripDto setSourceStopName(final String sourceStopName) {
        this.sourceStopName = sourceStopName;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripDto setDestinationStopCode(final String destinationStopCode) {
        this.destinationStopCode = destinationStopCode;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripDto setDestinationStopName(final String destinationStopName) {
        this.destinationStopName = destinationStopName;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripDto setBusCode(final String busCode) {
        this.busCode = busCode;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripDto setAgencyCode(final String agencyCode) {
        this.agencyCode = agencyCode;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripDto() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "TripDto(id=" + this.getId() + ", fare=" + this.getFare() + ", journeyTime=" + this.getJourneyTime() + ", sourceStopCode=" + this.getSourceStopCode() + ", sourceStopName=" + this.getSourceStopName() + ", destinationStopCode=" + this.getDestinationStopCode() + ", destinationStopName=" + this.getDestinationStopName() + ", busCode=" + this.getBusCode() + ", agencyCode=" + this.getAgencyCode() + ")";
    }
}
