// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.dto.model.bus;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Created by Arpit Khandelwal.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class TripScheduleDto {
    private String id;
    private String tripId;
    private String tripDate;
    private int availableSeats;
    private int fare;
    private int journeyTime;
    private String busCode;
    private String sourceStop;
    private String destinationStop;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getTripId() {
        return this.tripId;
    }

    @java.lang.SuppressWarnings("all")
    public String getTripDate() {
        return this.tripDate;
    }

    @java.lang.SuppressWarnings("all")
    public int getAvailableSeats() {
        return this.availableSeats;
    }

    @java.lang.SuppressWarnings("all")
    public int getFare() {
        return this.fare;
    }

    @java.lang.SuppressWarnings("all")
    public int getJourneyTime() {
        return this.journeyTime;
    }

    @java.lang.SuppressWarnings("all")
    public String getBusCode() {
        return this.busCode;
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceStop() {
        return this.sourceStop;
    }

    @java.lang.SuppressWarnings("all")
    public String getDestinationStop() {
        return this.destinationStop;
    }

    @java.lang.SuppressWarnings("all")
    public TripScheduleDto setId(final String id) {
        this.id = id;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripScheduleDto setTripId(final String tripId) {
        this.tripId = tripId;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripScheduleDto setTripDate(final String tripDate) {
        this.tripDate = tripDate;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripScheduleDto setAvailableSeats(final int availableSeats) {
        this.availableSeats = availableSeats;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripScheduleDto setFare(final int fare) {
        this.fare = fare;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripScheduleDto setJourneyTime(final int journeyTime) {
        this.journeyTime = journeyTime;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripScheduleDto setBusCode(final String busCode) {
        this.busCode = busCode;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripScheduleDto setSourceStop(final String sourceStop) {
        this.sourceStop = sourceStop;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripScheduleDto setDestinationStop(final String destinationStop) {
        this.destinationStop = destinationStop;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripScheduleDto() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "TripScheduleDto(id=" + this.getId() + ", tripId=" + this.getTripId() + ", tripDate=" + this.getTripDate() + ", availableSeats=" + this.getAvailableSeats() + ", fare=" + this.getFare() + ", journeyTime=" + this.getJourneyTime() + ", busCode=" + this.getBusCode() + ", sourceStop=" + this.getSourceStop() + ", destinationStop=" + this.getDestinationStop() + ")";
    }
}
