// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.model.bus;

import com.starterkit.springboot.brs.model.user.User;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.IndexDirection;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Set;

/**
 * Created by Arpit Khandelwal.
 */
@Document(collection = "agency")
public class Agency {
    @Id
    private String id;
    @Indexed(unique = true, direction = IndexDirection.DESCENDING, dropDups = true)
    private String code;
    @Indexed(unique = true, direction = IndexDirection.DESCENDING, dropDups = true)
    private String name;
    private String details;
    @DBRef(lazy = true)
    private User owner;
    @DBRef(lazy = true)
    private Set<Bus> buses;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDetails() {
        return this.details;
    }

    @java.lang.SuppressWarnings("all")
    public User getOwner() {
        return this.owner;
    }

    @java.lang.SuppressWarnings("all")
    public Set<Bus> getBuses() {
        return this.buses;
    }

    @java.lang.SuppressWarnings("all")
    public Agency setId(final String id) {
        this.id = id;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Agency setCode(final String code) {
        this.code = code;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Agency setName(final String name) {
        this.name = name;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Agency setDetails(final String details) {
        this.details = details;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Agency setOwner(final User owner) {
        this.owner = owner;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Agency setBuses(final Set<Bus> buses) {
        this.buses = buses;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Agency() {
    }
}
