// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.model.bus;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.IndexDirection;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Created by Arpit Khandelwal.
 */
@Document(collection = "bus")
public class Bus {
    @Id
    private String id;
    @Indexed(unique = true, direction = IndexDirection.DESCENDING, dropDups = true)
    private String code;
    private int capacity;
    private String make;
    @DBRef(lazy = true)
    private Agency agency;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    public int getCapacity() {
        return this.capacity;
    }

    @java.lang.SuppressWarnings("all")
    public String getMake() {
        return this.make;
    }

    @java.lang.SuppressWarnings("all")
    public Agency getAgency() {
        return this.agency;
    }

    @java.lang.SuppressWarnings("all")
    public Bus setId(final String id) {
        this.id = id;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Bus setCode(final String code) {
        this.code = code;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Bus setCapacity(final int capacity) {
        this.capacity = capacity;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Bus setMake(final String make) {
        this.make = make;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Bus setAgency(final Agency agency) {
        this.agency = agency;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Bus() {
    }
}
