// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.model.bus;

import com.starterkit.springboot.brs.model.user.User;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Created by Arpit Khandelwal.
 */
@Document(collection = "ticket")
public class Ticket {
    @Id
    private String id;
    private int seatNumber;
    private boolean cancellable;
    private String journeyDate;
    @DBRef
    private TripSchedule tripSchedule;
    @DBRef
    private User passenger;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public int getSeatNumber() {
        return this.seatNumber;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isCancellable() {
        return this.cancellable;
    }

    @java.lang.SuppressWarnings("all")
    public String getJourneyDate() {
        return this.journeyDate;
    }

    @java.lang.SuppressWarnings("all")
    public TripSchedule getTripSchedule() {
        return this.tripSchedule;
    }

    @java.lang.SuppressWarnings("all")
    public User getPassenger() {
        return this.passenger;
    }

    @java.lang.SuppressWarnings("all")
    public Ticket setId(final String id) {
        this.id = id;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Ticket setSeatNumber(final int seatNumber) {
        this.seatNumber = seatNumber;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Ticket setCancellable(final boolean cancellable) {
        this.cancellable = cancellable;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Ticket setJourneyDate(final String journeyDate) {
        this.journeyDate = journeyDate;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Ticket setTripSchedule(final TripSchedule tripSchedule) {
        this.tripSchedule = tripSchedule;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Ticket setPassenger(final User passenger) {
        this.passenger = passenger;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Ticket() {
    }
}
