// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.model.bus;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Created by Arpit Khandelwal.
 */
@Document(collection = "trip")
public class Trip {
    @Id
    private String id;
    private int fare;
    private int journeyTime;
    @DBRef
    private Stop sourceStop;
    @DBRef
    private Stop destStop;
    @DBRef
    private Bus bus;
    @DBRef
    private Agency agency;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public int getFare() {
        return this.fare;
    }

    @java.lang.SuppressWarnings("all")
    public int getJourneyTime() {
        return this.journeyTime;
    }

    @java.lang.SuppressWarnings("all")
    public Stop getSourceStop() {
        return this.sourceStop;
    }

    @java.lang.SuppressWarnings("all")
    public Stop getDestStop() {
        return this.destStop;
    }

    @java.lang.SuppressWarnings("all")
    public Bus getBus() {
        return this.bus;
    }

    @java.lang.SuppressWarnings("all")
    public Agency getAgency() {
        return this.agency;
    }

    @java.lang.SuppressWarnings("all")
    public Trip setId(final String id) {
        this.id = id;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Trip setFare(final int fare) {
        this.fare = fare;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Trip setJourneyTime(final int journeyTime) {
        this.journeyTime = journeyTime;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Trip setSourceStop(final Stop sourceStop) {
        this.sourceStop = sourceStop;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Trip setDestStop(final Stop destStop) {
        this.destStop = destStop;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Trip setBus(final Bus bus) {
        this.bus = bus;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Trip setAgency(final Agency agency) {
        this.agency = agency;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Trip() {
    }
}
