// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.model.bus;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.List;

/**
 * Created by Arpit Khandelwal.
 */
@Document(collection = "tripschedule")
public class TripSchedule {
    @Id
    private String id;
    @DBRef
    private Trip tripDetail;
    @DBRef(lazy = true)
    private List<Ticket> ticketsSold;
    private String tripDate;
    private int availableSeats;

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Trip getTripDetail() {
        return this.tripDetail;
    }

    @java.lang.SuppressWarnings("all")
    public List<Ticket> getTicketsSold() {
        return this.ticketsSold;
    }

    @java.lang.SuppressWarnings("all")
    public String getTripDate() {
        return this.tripDate;
    }

    @java.lang.SuppressWarnings("all")
    public int getAvailableSeats() {
        return this.availableSeats;
    }

    @java.lang.SuppressWarnings("all")
    public TripSchedule setId(final String id) {
        this.id = id;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripSchedule setTripDetail(final Trip tripDetail) {
        this.tripDetail = tripDetail;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripSchedule setTicketsSold(final List<Ticket> ticketsSold) {
        this.ticketsSold = ticketsSold;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripSchedule setTripDate(final String tripDate) {
        this.tripDate = tripDate;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripSchedule setAvailableSeats(final int availableSeats) {
        this.availableSeats = availableSeats;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripSchedule() {
    }
}
