// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.dto.model.user;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.Set;

/**
 * Created by Arpit Khandelwal.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class UserDto {
    private String email;
    private String password;
    private String firstName;
    private String lastName;
    private String mobileNumber;
    private boolean isAdmin;
    private Set<RoleDto> roles;

    public String getFullName() {
        return firstName != null ? firstName.concat(" ").concat(lastName) : "";
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    public String getFirstName() {
        return this.firstName;
    }

    @java.lang.SuppressWarnings("all")
    public String getLastName() {
        return this.lastName;
    }

    @java.lang.SuppressWarnings("all")
    public String getMobileNumber() {
        return this.mobileNumber;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isAdmin() {
        return this.isAdmin;
    }

    @java.lang.SuppressWarnings("all")
    public Set<RoleDto> getRoles() {
        return this.roles;
    }

    @java.lang.SuppressWarnings("all")
    public UserDto setEmail(final String email) {
        this.email = email;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserDto setPassword(final String password) {
        this.password = password;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserDto setFirstName(final String firstName) {
        this.firstName = firstName;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserDto setLastName(final String lastName) {
        this.lastName = lastName;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserDto setMobileNumber(final String mobileNumber) {
        this.mobileNumber = mobileNumber;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserDto setAdmin(final boolean isAdmin) {
        this.isAdmin = isAdmin;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserDto setRoles(final Set<RoleDto> roles) {
        this.roles = roles;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserDto() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "UserDto(email=" + this.getEmail() + ", password=" + this.getPassword() + ", firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", mobileNumber=" + this.getMobileNumber() + ", isAdmin=" + this.isAdmin() + ", roles=" + this.getRoles() + ")";
    }
}
