// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.controller.v1.command;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

/**
 * Created by Arpit Khandelwal.
 */
public class AgencyFormCommand {
    @NotBlank
    @Size(min = 5, max = 100)
    private String agencyName;
    @NotBlank
    @Size(max = 100)
    private String agencyDetails;

    @java.lang.SuppressWarnings("all")
    public AgencyFormCommand() {
    }

    @java.lang.SuppressWarnings("all")
    public String getAgencyName() {
        return this.agencyName;
    }

    @java.lang.SuppressWarnings("all")
    public String getAgencyDetails() {
        return this.agencyDetails;
    }

    @java.lang.SuppressWarnings("all")
    public AgencyFormCommand setAgencyName(final String agencyName) {
        this.agencyName = agencyName;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AgencyFormCommand setAgencyDetails(final String agencyDetails) {
        this.agencyDetails = agencyDetails;
        return this;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AgencyFormCommand)) return false;
        final AgencyFormCommand other = (AgencyFormCommand) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$agencyName = this.getAgencyName();
        final java.lang.Object other$agencyName = other.getAgencyName();
        if (this$agencyName == null ? other$agencyName != null : !this$agencyName.equals(other$agencyName)) return false;
        final java.lang.Object this$agencyDetails = this.getAgencyDetails();
        final java.lang.Object other$agencyDetails = other.getAgencyDetails();
        if (this$agencyDetails == null ? other$agencyDetails != null : !this$agencyDetails.equals(other$agencyDetails)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AgencyFormCommand;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $agencyName = this.getAgencyName();
        result = result * PRIME + ($agencyName == null ? 43 : $agencyName.hashCode());
        final java.lang.Object $agencyDetails = this.getAgencyDetails();
        result = result * PRIME + ($agencyDetails == null ? 43 : $agencyDetails.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AgencyFormCommand(agencyName=" + this.getAgencyName() + ", agencyDetails=" + this.getAgencyDetails() + ")";
    }
}
