// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.controller.v1.command;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

/**
 * Created by Arpit Khandelwal.
 */
public class BusFormCommand {
    @NotBlank
    @Size(min = 4, max = 8)
    private String code;
    @Min(value = 10, message = "Cannot enroll a bus with capacity smaller than 10")
    private int capacity;
    @NotBlank
    private String make;

    @java.lang.SuppressWarnings("all")
    public BusFormCommand() {
    }

    @java.lang.SuppressWarnings("all")
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    public int getCapacity() {
        return this.capacity;
    }

    @java.lang.SuppressWarnings("all")
    public String getMake() {
        return this.make;
    }

    @java.lang.SuppressWarnings("all")
    public BusFormCommand setCode(final String code) {
        this.code = code;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BusFormCommand setCapacity(final int capacity) {
        this.capacity = capacity;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BusFormCommand setMake(final String make) {
        this.make = make;
        return this;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BusFormCommand)) return false;
        final BusFormCommand other = (BusFormCommand) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$code = this.getCode();
        final java.lang.Object other$code = other.getCode();
        if (this$code == null ? other$code != null : !this$code.equals(other$code)) return false;
        if (this.getCapacity() != other.getCapacity()) return false;
        final java.lang.Object this$make = this.getMake();
        final java.lang.Object other$make = other.getMake();
        if (this$make == null ? other$make != null : !this$make.equals(other$make)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BusFormCommand;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $code = this.getCode();
        result = result * PRIME + ($code == null ? 43 : $code.hashCode());
        result = result * PRIME + this.getCapacity();
        final java.lang.Object $make = this.getMake();
        result = result * PRIME + ($make == null ? 43 : $make.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BusFormCommand(code=" + this.getCode() + ", capacity=" + this.getCapacity() + ", make=" + this.getMake() + ")";
    }
}
