// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.controller.v1.command;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

/**
 * Created by Arpit Khandelwal.
 */
public class ProfileFormCommand {
    @NotBlank
    @Size(min = 1, max = 40)
    private String firstName;
    @NotBlank
    private String lastName;
    @NotBlank
    @Size(min = 5, max = 13)
    private String mobileNumber;

    @java.lang.SuppressWarnings("all")
    public ProfileFormCommand() {
    }

    @java.lang.SuppressWarnings("all")
    public String getFirstName() {
        return this.firstName;
    }

    @java.lang.SuppressWarnings("all")
    public String getLastName() {
        return this.lastName;
    }

    @java.lang.SuppressWarnings("all")
    public String getMobileNumber() {
        return this.mobileNumber;
    }

    @java.lang.SuppressWarnings("all")
    public ProfileFormCommand setFirstName(final String firstName) {
        this.firstName = firstName;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ProfileFormCommand setLastName(final String lastName) {
        this.lastName = lastName;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ProfileFormCommand setMobileNumber(final String mobileNumber) {
        this.mobileNumber = mobileNumber;
        return this;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ProfileFormCommand)) return false;
        final ProfileFormCommand other = (ProfileFormCommand) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$firstName = this.getFirstName();
        final java.lang.Object other$firstName = other.getFirstName();
        if (this$firstName == null ? other$firstName != null : !this$firstName.equals(other$firstName)) return false;
        final java.lang.Object this$lastName = this.getLastName();
        final java.lang.Object other$lastName = other.getLastName();
        if (this$lastName == null ? other$lastName != null : !this$lastName.equals(other$lastName)) return false;
        final java.lang.Object this$mobileNumber = this.getMobileNumber();
        final java.lang.Object other$mobileNumber = other.getMobileNumber();
        if (this$mobileNumber == null ? other$mobileNumber != null : !this$mobileNumber.equals(other$mobileNumber)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ProfileFormCommand;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $firstName = this.getFirstName();
        result = result * PRIME + ($firstName == null ? 43 : $firstName.hashCode());
        final java.lang.Object $lastName = this.getLastName();
        result = result * PRIME + ($lastName == null ? 43 : $lastName.hashCode());
        final java.lang.Object $mobileNumber = this.getMobileNumber();
        result = result * PRIME + ($mobileNumber == null ? 43 : $mobileNumber.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ProfileFormCommand(firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", mobileNumber=" + this.getMobileNumber() + ")";
    }
}
