// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.controller.v1.command;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Positive;

/**
 * Created by Arpit Khandelwal.
 */
public class TripFormCommand {
    @NotBlank
    private String sourceStop;
    @NotBlank
    private String destinationStop;
    @NotBlank
    private String busCode;
    @Positive
    private int tripDuration;
    @Positive
    private int tripFare;

    @java.lang.SuppressWarnings("all")
    public TripFormCommand() {
    }

    @java.lang.SuppressWarnings("all")
    public String getSourceStop() {
        return this.sourceStop;
    }

    @java.lang.SuppressWarnings("all")
    public String getDestinationStop() {
        return this.destinationStop;
    }

    @java.lang.SuppressWarnings("all")
    public String getBusCode() {
        return this.busCode;
    }

    @java.lang.SuppressWarnings("all")
    public int getTripDuration() {
        return this.tripDuration;
    }

    @java.lang.SuppressWarnings("all")
    public int getTripFare() {
        return this.tripFare;
    }

    @java.lang.SuppressWarnings("all")
    public TripFormCommand setSourceStop(final String sourceStop) {
        this.sourceStop = sourceStop;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripFormCommand setDestinationStop(final String destinationStop) {
        this.destinationStop = destinationStop;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripFormCommand setBusCode(final String busCode) {
        this.busCode = busCode;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripFormCommand setTripDuration(final int tripDuration) {
        this.tripDuration = tripDuration;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TripFormCommand setTripFare(final int tripFare) {
        this.tripFare = tripFare;
        return this;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TripFormCommand)) return false;
        final TripFormCommand other = (TripFormCommand) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$sourceStop = this.getSourceStop();
        final java.lang.Object other$sourceStop = other.getSourceStop();
        if (this$sourceStop == null ? other$sourceStop != null : !this$sourceStop.equals(other$sourceStop)) return false;
        final java.lang.Object this$destinationStop = this.getDestinationStop();
        final java.lang.Object other$destinationStop = other.getDestinationStop();
        if (this$destinationStop == null ? other$destinationStop != null : !this$destinationStop.equals(other$destinationStop)) return false;
        final java.lang.Object this$busCode = this.getBusCode();
        final java.lang.Object other$busCode = other.getBusCode();
        if (this$busCode == null ? other$busCode != null : !this$busCode.equals(other$busCode)) return false;
        if (this.getTripDuration() != other.getTripDuration()) return false;
        if (this.getTripFare() != other.getTripFare()) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TripFormCommand;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $sourceStop = this.getSourceStop();
        result = result * PRIME + ($sourceStop == null ? 43 : $sourceStop.hashCode());
        final java.lang.Object $destinationStop = this.getDestinationStop();
        result = result * PRIME + ($destinationStop == null ? 43 : $destinationStop.hashCode());
        final java.lang.Object $busCode = this.getBusCode();
        result = result * PRIME + ($busCode == null ? 43 : $busCode.hashCode());
        result = result * PRIME + this.getTripDuration();
        result = result * PRIME + this.getTripFare();
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "TripFormCommand(sourceStop=" + this.getSourceStop() + ", destinationStop=" + this.getDestinationStop() + ", busCode=" + this.getBusCode() + ", tripDuration=" + this.getTripDuration() + ", tripFare=" + this.getTripFare() + ")";
    }
}
