// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.controller.v1.request;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * Created by Arpit Khandelwal.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class BookTicketRequest {
    @NotEmpty(message = "{constraints.NotEmpty.message}")
    private String tripID;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @NotNull(message = "{constraints.NotEmpty.message}")
    @Temporal(TemporalType.DATE)
    private Date tripDate;

    @java.lang.SuppressWarnings("all")
    public String getTripID() {
        return this.tripID;
    }

    @java.lang.SuppressWarnings("all")
    public Date getTripDate() {
        return this.tripDate;
    }

    @java.lang.SuppressWarnings("all")
    public BookTicketRequest setTripID(final String tripID) {
        this.tripID = tripID;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BookTicketRequest setTripDate(final Date tripDate) {
        this.tripDate = tripDate;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BookTicketRequest() {
    }
}
