// Generated by delombok at Thu Dec 05 17:52:13 EST 2019
package com.starterkit.springboot.brs.controller.v1.request;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.validation.constraints.NotEmpty;

/**
 * Created by Arpit Khandelwal.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class UserSignupRequest {
    @NotEmpty(message = "{constraints.NotEmpty.message}")
    private String email;
    @NotEmpty(message = "{constraints.NotEmpty.message}")
    private String password;
    @NotEmpty(message = "{constraints.NotEmpty.message}")
    private String firstName;
    @NotEmpty(message = "{constraints.NotEmpty.message}")
    private String lastName;
    private String mobileNumber;

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    public String getFirstName() {
        return this.firstName;
    }

    @java.lang.SuppressWarnings("all")
    public String getLastName() {
        return this.lastName;
    }

    @java.lang.SuppressWarnings("all")
    public String getMobileNumber() {
        return this.mobileNumber;
    }

    @java.lang.SuppressWarnings("all")
    public UserSignupRequest setEmail(final String email) {
        this.email = email;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserSignupRequest setPassword(final String password) {
        this.password = password;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserSignupRequest setFirstName(final String firstName) {
        this.firstName = firstName;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserSignupRequest setLastName(final String lastName) {
        this.lastName = lastName;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserSignupRequest setMobileNumber(final String mobileNumber) {
        this.mobileNumber = mobileNumber;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public UserSignupRequest() {
    }
}
